Repository sccp2020/defective-project, pull requests merged in 2019-12, with the labels that each got.

#53 fix type-round_off_nth_digit
  src/type/round_off_nth_digit.py
Labels: completed

#54 fix algorithm/test_isort_hard
  src/algorithm/isort_hard.py
Labels: completed, solved

#51 modify
  src/type/round_off_nth_digit.py
Labels: improve

#59 fix leap_year_normal.py
  src/algorithm/leap_year_normal.py
Labels: completed

#58 fix type-change_zero_last_bits
  src/type/change_zero_last_bits.py
Labels: completed

#62 fix algorithm/pascals_triangle_hard
  src/algorithm/pascals_triangle_hard.py
Labels: completed

#61 fix algorithm-lcm_normal
  src/algorithm/lcm_normal.py
Labels: completed

#66 fix algorithm/fib_normal
  src/algorithm/fib_normal.py
Labels: completed
